merge -out cov_merged_output test*
load -run ./cov_work/scope/cov_merged_output/
exclude -inst csr_top -toggle {mvendorid[0-63]}
exclude -inst csr_top -toggle {marchid[0-63]}
exclude -inst csr_top -toggle {mimpid[0-63]}
exclude -inst csr_top -toggle {mhartid[0-63]}
exclude -inst csr_top -toggle {medeleg[0-63]}
exclude -inst csr_top -toggle {marchid[0-63]}
exclude -inst csr_top -toggle {mideleg[0-63]}
exclude -inst csr_top -toggle {misa[0-63]}
exclude -inst csr_top -toggle {mcounter[0-63]}
exclude -inst csr_top -toggle {mstatus[0-2]}
exclude -inst csr_top -toggle {mstatus[4-6]}
exclude -inst csr_top -toggle {mstatus[8-63]}
exclude -inst csr_top -toggle {mie[0-2]}
exclude -inst csr_top -toggle {mie[4-6]}
exclude -inst csr_top -toggle {mie[8-10]}
exclude -inst csr_top -toggle {mie[12-63]}
exclude -inst csr_top -toggle {mip[0-2]}
exclude -inst csr_top -toggle {mip[4-6]}
exclude -inst csr_top -toggle {mip[8-10]}
exclude -inst csr_top -toggle {mip[12-63]}
exclude -inst csr_top -toggle {interrupt_active_level_priority_w[8-63]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mvendorid_i[0-63]}
exclude -inst csr_top.csr_read_mux_inst -toggle {marchid_i[0-63]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mimpid_i[0-63]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mhartid_i[0-63]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mstatus_i[0-2]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mstatus_i[4-6]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mstatus_i[8-63]}
exclude -inst csr_top.csr_read_mux_inst -toggle {misa_i[0-63]}
exclude -inst csr_top.csr_read_mux_inst -toggle {medeleg_i[0-63]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mideleg_i[0-63]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mie_i[0-2]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mie_i[4-6]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mie_i[8-10]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mie_i[12-63]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mcounter_i[0-63]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mip_i[0-2]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mip_i[4-6]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mip_i[8-10]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mip_i[12-63]}
exclude -inst csr_top.csr_read_mux_inst -toggle {interrupt_active_level_priority_i[8-63]}
exclude -inst csr_top.csr_register_file_inst -toggle {interrupt_active_level_priority_o[8-63]}
exclude -inst csr_top.csr_register_file_inst -toggle {mvendorid_o[0-63]}
exclude -inst csr_top.csr_register_file_inst -toggle {marchid_o[0-63]}
exclude -inst csr_top.csr_register_file_inst -toggle {mimpid_o[0-63]}
exclude -inst csr_top.csr_register_file_inst -toggle {mhartid_o[0-63]}
exclude -inst csr_top.csr_register_file_inst -toggle {mstatus_o[0-2]}
exclude -inst csr_top.csr_register_file_inst -toggle {mstatus_o[4-6]}
exclude -inst csr_top.csr_register_file_inst -toggle {mstatus_o[8-63]}
exclude -inst csr_top.csr_register_file_inst -toggle {misa_o[0-63]}
exclude -inst csr_top.csr_register_file_inst -toggle {medeleg_o[0-63]}
exclude -inst csr_top.csr_register_file_inst -toggle {mideleg_o[0-63]}
exclude -inst csr_top.csr_register_file_inst -toggle {mie_o[0-2]}
exclude -inst csr_top.csr_register_file_inst -toggle {mie_o[4-6]}
exclude -inst csr_top.csr_register_file_inst -toggle {mie_o[8-10]}
exclude -inst csr_top.csr_register_file_inst -toggle {mie_o[12-63]}
exclude -inst csr_top.csr_register_file_inst -toggle {mcounter_o[0-63]}
exclude -inst csr_top.csr_register_file_inst -toggle {mip_o[0-2]}
exclude -inst csr_top.csr_register_file_inst -toggle {mip_o[4-6]}
exclude -inst csr_top.csr_register_file_inst -toggle {mip_o[8-10]}
exclude -inst csr_top.csr_register_file_inst -toggle {mip_o[12-63]}
exclude -inst csr_top.csr_register_file_inst.march_csr_inst -toggle {march_id_o[0-63]}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {misa_csr_o[0-63]}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {isa_type[0-1]}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {A}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {B}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {C}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {D}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {E}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {F}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {G}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {H}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {I}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {J}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {K}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {L}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {M}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {N}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {O}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {P}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {Q}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {R}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {S}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {T}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {U}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {V}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {W}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {X}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {Y}
exclude -inst csr_top.csr_register_file_inst.misa_csr_inst -toggle {Z}
exclude -inst csr_top.csr_register_file_inst.mvendorid_csr_inst -toggle {mvendor_id_o[0-63]}
exclude -inst csr_top.csr_register_file_inst.mimpid_csr_inst -toggle {mimp_id_o[0-63]}
exclude -inst csr_top.csr_register_file_inst.mhardid_csr_inst -toggle {mhart_id_o[0-63]}
exclude -inst csr_top.csr_register_file_inst.mstatus_csr_inst -toggle {mstatus_o[0-2]}
exclude -inst csr_top.csr_register_file_inst.mstatus_csr_inst -toggle {mstatus_o[4-6]}
exclude -inst csr_top.csr_register_file_inst.mstatus_csr_inst -toggle {mstatus_o[8-63]}
exclude -inst csr_top.csr_register_file_inst.mcause_csr_inst -toggle {prev_int_lvl_pr_r[0-7]}
exclude -inst csr_top.csr_register_file_inst.mip_csr_inst -toggle {mip_o[0-2]}
exclude -inst csr_top.csr_register_file_inst.mip_csr_inst -toggle {mip_o[4-6]}
exclude -inst csr_top.csr_register_file_inst.mip_csr_inst -toggle {mip_o[8-10]}
exclude -inst csr_top.csr_register_file_inst.mip_csr_inst -toggle {mip_o[12-63]}
exclude -inst csr_top.csr_register_file_inst.mie_csr_inst -toggle {mie_o[0-2]}
exclude -inst csr_top.csr_register_file_inst.mie_csr_inst -toggle {mie_o[4-6]}
exclude -inst csr_top.csr_register_file_inst.mie_csr_inst -toggle {mie_o[8-10]}
exclude -inst csr_top.csr_register_file_inst.mie_csr_inst -toggle {mie_o[12-63]}
exclude -inst csr_top.csr_register_file_inst.mtvec_csr_inst -toggle mode\[0-1\]
exclude -inst csr_top.csr_register_file_inst.mintstatus_csr_inst -toggle interrupt_active_level_priority_o\[8-63\]
exclude -inst csr_top.csr_read_mux_inst -block {medeleg_i[9]}
exclude -inst csr_top.csr_read_mux_inst -block {mideleg_i[10]}
exclude -inst csr_top.csr_read_mux_inst -block {mcounter_i[13]}
exclude -inst csr_top -toggle csr_mtvec_o\[1\]
exclude -inst csr_top -toggle csr_mtvec_o\[0\]
exclude -inst csr_top.csr_read_mux_inst -toggle {mtvec_i[1]}
exclude -inst csr_top.csr_read_mux_inst -toggle {mtvec_i[0]}
exclude -inst csr_top.csr_register_file_inst -toggle {mtvec_o[1]}
exclude -inst csr_top.csr_register_file_inst -toggle {mtvec_o[0]}
exclude -inst csr_top.csr_register_file_inst.mtvec_csr_inst toggle {mtvec_o[1]}
exclude -inst csr_top.csr_register_file_inst.mtvec_csr_inst toggle {mtvec_o[0]}
report -detail -all -text -out cov_report.txt
report -detail -text -out cov_uncovered_report.txt
report -detail -html -out ./cov_report_html
